version: '3.8'

services:
  agent:
    image: portainer/agent:2.25.1
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    networks:
      - agent-network

  portainer:
    image: portainer/portainer-ce:2.25.1
    restart: unless-stopped
    command: "-H tcp://agent:9001 --tlsskipverify"
    volumes:
      - "/mnt/portainer:/data"
    networks:
      - traefik3-public
      - agent-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik3-public"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.middlewares=default-ipallowlist@file"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=certresolver-mvp"

networks:
  agent-network:
    driver: bridge
  traefik3-public:
    external: true
