global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['reverse-proxy:8082']  # Traefik Prometheus metrics endpoint